import { Guest } from "../interfaces/guests";

export const allGuests: Guest[] = [
  {
    code: "ml-mj01",
    id: "mejia jaramillo",
    adults: ["Nancy Mejía"],
    kids: [],
  },
  {
    code: "ml-mj57",
    id: "mejia jaramillo",
    adults: ["Beatriz Mejía", "Mariela Mejía"],
    kids: [],
  },
  {
    code: "ml-pm02",
    id: "pellon",
    adults: ["Robert Pellón", "Margarita Mejía"],
    kids: [],
  },
  {
    code: "ml-lr03",
    id: "lópez restrepo",
    adults: ["Daniel López", "Natalia Restrepo"],
    kids: [],
  },
  {
    code: "ml-mc04",
    id: "mejia cardona",
    adults: ["Sebastian Mejía", "Laura Vanessa Cardona"],
    kids: [],
  },
  {
    code: "ml-mm05",
    id: "mejia morales",
    adults: ["William Mejía", "Aleida Morales", "William Alejandro Mejía"],
    kids: [],
  },
  {
    code: "ml-m06",
    id: "muñoz",
    adults: ["Dubán Muñoz"],
    kids: [],
  },
  {
    code: "ml-rm07",
    id: "rojas mejia",
    adults: ["Jorge Anibal Rojas", "Liliana Mejía"],
    kids: [],
  },
  {
    code: "ml-om08",
    id: "osorio",
    adults: ["Nick Osorio", "Juliana del Mar"],
    kids: [],
  },
  {
    code: "ml-am09",
    id: "abdalá mejía",
    adults: ["Yussyf Abdalá", "Maria Elena Mejía"],
    kids: [],
  },
  {
    code: "ml-sm10",
    id: "soulie mejía",
    adults: ["Christophe Soulie", "Carolina Mejía"],
    kids: [],
  },
  {
    code: "ml-al11",
    id: "aguilar lópez",
    adults: ["Carlos Aguilar", "Gloria Inés López"],
    kids: [],
  },
  {
    code: "ml-l12",
    id: "lópez",
    adults: ["Jhon Freddy López"],
    kids: [],
  },
  {
    code: "ml-a13",
    id: "alarcón",
    adults: ["Luz Amparo Alarcón"],
    kids: [],
  },
  {
    code: "ml-f14",
    id: "florez",
    adults: ["Fernando Flórez", "Mateo Flórez"],
    kids: [],
  },
  {
    code: "ml-f58",
    id: "florez",
    adults: ["Mateo Flórez"],
    kids: [],
  },
  {
    code: "ml-o15",
    id: "ocampo",
    adults: ["Nubia Ocampo"],
    kids: [],
  },
  {
    code: "ml-ad16",
    id: "arcila diaz",
    adults: ["John Jairo Arcila", "Patricia del Pilar Diaz"],
    kids: [],
  },
  {
    code: "ml-gv17",
    id: "gallego vásquez",
    adults: ["Juan Felipe Gallego Vasquez"],
    kids: [],
  },
  {
    code: "ml-gt18",
    id: "gutierrez trujillo",
    adults: ["Estephania Gutierrez Trujillo"],
    kids: [],
  },
  {
    code: "ml-gb19",
    id: "gómez bustamante",
    adults: ["Gonzalo Gómez", "Natalia Bustamante"],
    kids: [],
  },
  {
    code: "ml-g20",
    id: "gómez",
    adults: ["Catalina Gómez Matallana", "Arturo Frieri"],
    kids: ["Arturo Frieri", "Vicente Frieri"],
  },
  {
    code: "ml-bd21",
    id: "bustamante duque",
    adults: ["Jairo Bustamante", "Alicia Duque"],
    kids: [],
  },
  {
    code: "ml-ab22",
    id: "aldana bustamante",
    adults: ["Fredy Aldana", "Jimena Bustamante"],
    kids: [],
  },
  {
    code: "ml-ag23",
    id: "aldana gómez",
    adults: ["Luis Aldana", "Deisy Gómez"],
    kids: [],
  },
  {
    code: "ml-ma24",
    id: "méndez aldana",
    adults: ["Yovanny Méndez", "Marcela Aldana", "Mariam Méndez"],
    kids: [],
  },
  {
    code: "ml-gr25",
    id: "gómez ramirez",
    adults: ["Fredy Gómez", "Ana Lucía Ramirez", "Sebastian Gómez"],
    kids: [],
  },
  {
    code: "ml-gm26",
    id: "gómez murillo",
    adults: ["Patricia Gómez Murillo", "Dilan Gómez"],
    kids: [],
  },
  {
    code: "ml-ab27",
    id: "aldana benavides",
    adults: ["Jhon Aldana", "Vanesa Benavides"],
    kids: [],
  },
  {
    code: "ml-dz28",
    id: "duque zuluaga",
    adults: ["Marina Duque Zuluaga"],
    kids: [],
  },
  {
    code: "ml-cl29",
    id: "castañeda largo",
    adults: ["Mercedes Largo", "Victoria Castañeda"],
    kids: [],
  },
  {
    code: "ml-bm30",
    id: "bustamante marin",
    adults: ["Juan Diego Bustamante", "Claudia Marín"],
    kids: [],
  },
  {
    code: "ml-b31",
    id: "betancourt",
    adults: ["Jhon Jairo Betancourt"],
    kids: [],
  },
  {
    code: "ml-lv32",
    id: "lópez valencia",
    adults: ["John Omar López", "Carolina Valencia"],
    kids: ["Lucía López Valencia"],
  },
  {
    code: "ml-ho33",
    id: "henao osorio",
    adults: ["Nátaly Henao Osorio"],
    kids: [],
  },
  {
    code: "ml-fg34",
    id: "fernández garzón",
    adults: ["Miguel Ángel Fernández", "Valentina Garzón"],
    kids: ["María Fernández Garzón"],
  },
  {
    code: "ml-bo35",
    id: "bedoya osorio",
    adults: ["Johan David Bedoya", "Maria Alejandra Osorio"],
    kids: ["Jacobo Osorio"],
  },
  {
    code: "ml-pv36",
    id: "pineda valencia",
    adults: ["Santiago Pineda", "Valentina Valencia"],
    kids: ["Samuel Pineda Valencia"],
  },
  {
    code: "ml-v37",
    id: "vargas",
    adults: ["Juan David Vargas"],
    kids: [],
  },
  {
    code: "ml-bc38",
    id: "bedoya correa",
    adults: ["Sebastian Bedoya Correa"],
    kids: [],
  },
  {
    code: "ml-gr39",
    id: "gil rengifo",
    adults: ["Juan Pablo Gil", "Paula Andrea Rengifo"],
    kids: [],
  },
  {
    code: "ml-c40",
    id: "ceballos",
    adults: ["James Daniel Ceballos"],
    kids: [],
  },
  {
    code: "ml-v41",
    id: "valencia",
    adults: ["Erika Johana Valencia", "Cristian Camilo Valencia"],
    kids: [],
  },
  {
    code: "ml-v59",
    id: "valencia",
    adults: ["Cristian Camilo Valencia"],
    kids: [],
  },
  {
    code: "ml-co42",
    id: "cifuentes ortiz",
    adults: ["Jhon Keddin Cifuentes", "Katheryn Ortiz"],
    kids: ["Juan José Cifuentes Ortiz"],
  },
  {
    code: "ml-g43",
    id: "gonzalez",
    adults: ["Juan José González"],
    kids: [],
  },
  {
    code: "ml-n44",
    id: "nieto",
    adults: ["Maria Alejandra Nieto"],
    kids: [],
  },
  {
    code: "ml-pp45",
    id: "pineda pérez",
    adults: ["Hector Fabio Pineda", "Lady Pérez", "Emmanuel Pineda"],
    kids: [],
  },
  {
    code: "ml-f46",
    id: "gómez",
    adults: ["Alexandra Gómez"],
    kids: [],
  },
  {
    code: "ml-va47",
    id: "valencia alvarez",
    adults: ["Sergio Esteban Valencia", "Daniela Alvarez"],
    kids: ["Alison Valencia Alvarez"],
  },
  {
    code: "ml-j48",
    id: "jaramillo",
    adults: ["Alejandra Jaramillo"],
    kids: [],
  },
  {
    code: "ml-zg49",
    id: "zuluaga gallego",
    adults: ["William Zuluaga", "Claudia Gallego"],
    kids: [],
  },
  {
    code: "ml-or50",
    id: "ortega restrepo",
    adults: ["Brandon Ortega", "Tatiana Restrepo"],
    kids: ["Alana Ortega Restrepo"],
  },
  {
    code: "ml-sg52",
    id: "sánchez gutierrez",
    adults: ["Marcel Sánchez", "Stefany Gutiérrez"],
    kids: [],
  },
  {
    code: "ml-cg53",
    id: "cardona gómez",
    adults: ["Santiago Cardona", "Carolina Gómez"],
    kids: ["Matias Cardona Gómez"],
  },
  {
    code: "ml-z54",
    id: "zapata",
    adults: ["Natalia Zapata"],
    kids: [],
  },
  {
    code: "ml-rc55",
    id: "ribadeneira chavez",
    adults: ["Rodrigo Ribadeneira chavéz"],
    kids: [],
  },
  {
    code: "ml-bd56",
    id: "bustamante dávila",
    adults: ["Adrian Felipe Bustamante Dávila, Paula Sánchez"],
    kids: [],
  },
];
